// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCHjCF8R2Pc_FfgkncSZNBPj5NZ9pvXFM',
    appId: '1:745364143027:web:9e939d34fc04b6635d69c6',
    messagingSenderId: '745364143027',
    projectId: 'evently-app-4a155',
    authDomain: 'evently-app-4a155.firebaseapp.com',
    storageBucket: 'evently-app-4a155.firebasestorage.app',
    measurementId: 'G-FFYGEXKR9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPIW3AlOz_xmo379E145v8yTZ7OKI_e7U',
    appId: '1:745364143027:android:bc90364aa06eaf105d69c6',
    messagingSenderId: '745364143027',
    projectId: 'evently-app-4a155',
    storageBucket: 'evently-app-4a155.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZimC-bF1k99HdSI35BJ0p5H7yhSsgB-Q',
    appId: '1:745364143027:ios:143b6eeb5a1135045d69c6',
    messagingSenderId: '745364143027',
    projectId: 'evently-app-4a155',
    storageBucket: 'evently-app-4a155.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZimC-bF1k99HdSI35BJ0p5H7yhSsgB-Q',
    appId: '1:745364143027:ios:143b6eeb5a1135045d69c6',
    messagingSenderId: '745364143027',
    projectId: 'evently-app-4a155',
    storageBucket: 'evently-app-4a155.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCHjCF8R2Pc_FfgkncSZNBPj5NZ9pvXFM',
    appId: '1:745364143027:web:82e472306c44542d5d69c6',
    messagingSenderId: '745364143027',
    projectId: 'evently-app-4a155',
    authDomain: 'evently-app-4a155.firebaseapp.com',
    storageBucket: 'evently-app-4a155.firebasestorage.app',
    measurementId: 'G-JPTWNSY2H7',
  );
}
